### ISSUE TITLE
говно

### ISSUE THREAD

**Issue by monobl0k** [Pelfox/pydisco#1]

**Comment by Pelfox** [comment]
спасибо за твою рецензию, но who asked?

**Comment by monobl0k** [comment]
> спасибо за твою рецензию, но who asked?

вы у меня говно украли верблюды

**Comment by RaynelX** [comment]
ну верните человеку его говно, шо вы как не русские

**Comment by Pelfox** [comment]
> ну верните человеку его говно, шо вы как не русские

молчать беыарпус

**Comment by RaynelX** [comment]
> > ну верните человеку его говно, шо вы как не русские
> 
> молчать беыарпус

беыарпус здесь только ты и твоё говно, которое тебе нужно сдать в залог, чтобы оплатить ипотеку.

**Comment by Pelfox** [comment]
> > > ну верните человеку его говно, шо вы как не русские
> > 
> > 
> > молчать беыарпус
> 
> беыарпус здесь только ты и твоё говно, которое тебе нужно сдать в залог, чтобы оплатить ипотеку.

WHO?
CARES?

**Comment by RaynelX** [comment]
> > > > ну верните человеку его говно, шо вы как не русские
> > > 
> > > 
> > > молчать беыарпус
> > 
> > 
> > беыарпус здесь только ты и твоё говно, которое тебе нужно сдать в залог, чтобы оплатить ипотеку.
> 
> WHO? CARES?

YOUR
MOTHER

**Comment by Pelfox** [comment]
@monobl0k биба?

**Comment by RaynelX** [comment]
боба

**Comment by Pelfox** [comment]
!close
